##spring.application.name=Hello-App
spring:
  application:
    name: Hello-App

  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

  info:
    git:
      enabled: true
      mode: full
